### ISSUE TITLE
please provide a precompiled dll

### ISSUE THREAD

**Issue by Bluscream** [techiew/UniversalProxyDLL#2]
Ideally one that allows setting the DLL path to inject via ENV variables or commandline args or a config file similar to https://github.com/NeighTools/UnityDoorstop?tab=readme-ov-file#doorstop-environment-variables

**Comment by techiew** [comment]
https://github.com/techiew/UniversalProxyDLL/releases/tag/precompiled-dll

**Comment by Bluscream** [comment]
Awesome !
